INSERT INTO productos (codigo, nombre, categoria, precio, stock, descripcion) VALUES
('P001', 'Smartphone', 'Electrónica', 699.99, 150, 'Teléfono inteligente de última generación con cámara de alta resolución.'),
('P002', 'Auriculares Inalámbricos', 'Electrónica', 99.50, 300, 'Auriculares con cancelación de ruido y batería de larga duración.'),
('P003', 'Laptop Ultradelgada', 'Informática', 1250.00, 75, 'Portátil ligero ideal para trabajo y estudio.'),
('P004', 'Teclado Mecánico RGB', 'Informática', 85.00, 200, 'Teclado para gamers con iluminación personalizable.'),
('P005', 'Ratón Inalámbrico', 'Informática', 25.00, 450, 'Ratón ergonómico con sensor de alta precisión.'),
('P006', 'Monitor 4K', 'Informática', 350.75, 90, 'Monitor de 27 pulgadas con resolución Ultra HD.'),
('P007', 'Mochila de Viaje', 'Accesorios', 55.00, 120, 'Mochila resistente al agua con múltiples compartimentos.'),
('P008', 'Cargador Portátil', 'Electrónica', 35.99, 500, 'Batería externa de 20000mAh para cargar dispositivos móviles.'),
('P009', 'Disco Duro Externo 1TB', 'Almacenamiento', 65.00, 180, 'Unidad de almacenamiento portátil de alta velocidad.'),
('P010', 'Impresora Multifuncional', 'Oficina', 199.99, 60, 'Impresora que escanea, copia y imprime a color.'),
('P011', 'Tablet de 10 pulgadas', 'Electrónica', 250.00, 110, 'Tableta versátil para entretenimiento y productividad.'),
('P012', 'Reloj Inteligente', 'Wearables', 149.99, 220, 'Reloj con monitor de actividad física y notificaciones.'),
('P013', 'Altavoz Bluetooth', 'Audio', 45.00, 280, 'Altavoz portátil con sonido envolvente y resistente al agua.'),
('P014', 'Router Wi-Fi 6', 'Redes', 89.90, 95, 'Router de alta velocidad para una conexión estable en el hogar.'),
('P015', 'Webcam Full HD', 'Periféricos', 39.50, 170, 'Cámara web para videoconferencias con calidad 1080p.'),
('P016', 'Software de Edición de Video', 'Software', 300.00, 50, 'Licencia anual para software profesional de edición.'),
('P017', 'Drone con Cámara', 'Drones', 450.00, 40, 'Dron compacto con cámara 4K para fotografía aérea.'),
('P018', 'Cable HDMI 2.1', 'Cables', 15.00, 600, 'Cable para transmitir video en alta definición.'),
('P019', 'Lámpara LED de Escritorio', 'Iluminación', 29.99, 350, 'Lámpara con brillo ajustable y puerto de carga USB.'),
('P020', 'Tarjeta Gráfica RTX 3060', 'Componentes PC', 420.00, 30, 'Tarjeta gráfica de alto rendimiento para gaming y diseño.');